# docker compose -f compose.yml -f compose.debug.yml up"

services:
  pipelines:
    ports:
      - 5678:5678
    entrypoint: [
      "python",
      "-m",
      "debugpy",
      "--wait-for-client",
      "--listen",
      "0.0.0.0:5678",
      "-m",
      "uvicorn",
      "main:app",
      "--host",
      "0.0.0.0",
      "--port",
      "9099",
      "--forwarded-allow-ips",
      "*"
    ]
