services:
  pipelines:
    build:
      dockerfile: ./Dockerfile.pipelines
    entrypoint: "uvicorn main:app --host 0.0.0.0 --port 9099 --forwarded-allow-ips * --reload"
    ports:
      - "9099:9099"
    volumes:
      - ./pipelines:/app/pipelines
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - dev/.env.pipelines
    depends_on:
      - db

  open-webui:
    build:
      dockerfile: ./Dockerfile.open-webui
    ports:
      - "8080:8080"
    environment:
      # - LOGO_IMAGE_URL=https://d7umqicpi7263.cloudfront.net/img/product/cba2a0f8-c16e-491c-975c-aae86876816f.com/f87179e091d7c516b594bbddf5e03c8d
      - OPENAI_API_BASE_URL=http://host.docker.internal:9099
      - OPENAI_API_KEY=0p3n-w3bu! # API key for the pipelines service (default, PIPELINES_API_KEY in deployments)
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres # PostgreSQL connection URL
      - DEFAULT_USER_ROLE=user
    env_file:
      - dev/.env.webui
    depends_on:
      - db
      - pipelines

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/postgres
    volumes:
      - db_data:/data/postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: # Persistent volume for PostgreSQL data
